// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD264KgN3DOSaZPygwvsor_5XhCqT4QNDQ',
    appId: '1:608352790558:web:5f7262f1bbe08720f1660f',
    messagingSenderId: '608352790558',
    projectId: 'chattaskapp01',
    authDomain: 'chattaskapp01.firebaseapp.com',
    storageBucket: 'chattaskapp01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSAx0wJ0hn5J8fpC0ls_ckC5VtNLUMoo',
    appId: '1:608352790558:android:359f92fd47411a81f1660f',
    messagingSenderId: '608352790558',
    projectId: 'chattaskapp01',
    storageBucket: 'chattaskapp01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAruYXg_944OGkO84q5rzH0x3Ar2IrHJkc',
    appId: '1:608352790558:ios:a8de3faba77422aff1660f',
    messagingSenderId: '608352790558',
    projectId: 'chattaskapp01',
    storageBucket: 'chattaskapp01.appspot.com',
    iosBundleId: 'com.example.chatTaskApp',
  );
}
